### ISSUE TITLE
React app does not update properly

### ISSUE THREAD

**Issue by medhatelmasry** [MicrosoftDocs/mslearn-staticwebapp#11]
I followed the instructions and successfully deployed your sample app to Azure Static Web Apps. I noticed that the react application does not update quantity properly. It does, however, update name and description - not quantity. Is this intentional or a bug?

**Comment by johnpapa** [comment]
This is indeed a bug, but in the API itself. I will push a fix shortly. Thank you for reporting this!

**Comment by johnpapa** [comment]
This is now resolved. Thanks again!
