### ISSUE TITLE
Node LTS Version

### ISSUE THREAD

**Issue by c0g1t8** [MicrosoftDocs/mslearn-staticwebapp#20]
The readme should include a recommendation to use the LTS version of Node - _Node v12.18.3_.    

I found the warning messages distracting when following the [tutorial](https://docs.microsoft.com/learn/modules/publish-app-service-static-web-app-api/?WT.mc_id=mslearn_staticwebapp-github-jopapa) with the current version of Node - _v14.7.0_ on the Mac.

**Comment by c0g1t8** [comment]
Repeated the build process in Windows using the same version of Node.  Found an issue when executing **npm run serve**.  An excerpt is below.

> error  in ./src/components/card-content.vue
> 
> Module Error (from ./node_modules/eslint-loader/index.js):
> 
> C:\repos\my-static-web-app\vue-app\src\components\card-content.vue
>    1:9   error  Delete `␍`  prettier/prettier
>    2:17  error  Delete `␍`  prettier/prettier
>    3:23  error  Delete `␍`  prettier/prettier
>    4:11  error  Delete `␍`  prettier/prettier
>    5:12  error  Delete `␍`  prettier/prettier
>    6:20  error  Delete `␍`  prettier/prettier
>    7:25  error  Delete `␍`  prettier/prettier
>    8:7   error  Delete `␍`  prettier/prettier
>    9:19  error  Delete `␍`  prettier/prettier
>   10:20  error  Delete `␍`  prettier/prettier
>   11:25  error  Delete `␍`  prettier/prettier
>   12:7   error  Delete `␍`  prettier/prettier
>   13:5   error  Delete `␍`  prettier/prettier
>   14:3   error  Delete `␍`  prettier/prettier
>   15:10  error  Delete `␍`  prettier/prettier
>   16:1   error  Delete `␍`  prettier/prettier
>   17:11  error  Delete `␍`  prettier/prettier
>   18:29  error  Delete `␍`  prettier/prettier
>   19:26  error  Delete `␍`  prettier/prettier
>   20:41  error  Delete `␍`  prettier/prettier
>   21:55  error  Delete `␍`  prettier/prettier
>   22:11  error  Delete `␍`  prettier/prettier
>   23:9   error  Delete `␍`  prettier/prettier
>   24:12  error  Delete `␍`  prettier/prettier
> 
> ✖ 24 problems (24 errors, 0 warnings)
>   24 errors and 0 warnings potentially fixable with the `--fix` option.

It's a know issue - https://stackoverflow.com/questions/53516594/why-do-i-keep-getting-delete-cr-prettier-prettier.

**Comment by c0g1t8** [comment]
Changed **.eslintrc.js** file to resolve as suggested in the _stackoverflow_ article.

![image](https://user-images.githubusercontent.com/23250332/89373894-b64e8f00-d69e-11ea-9b03-24579b34d559.png)

Should this be in the default template?

**Comment by johnpapa** [comment]
thanks. I added the LTS to the readme
