### ISSUE TITLE
vue-app build fails due to eslint error

### ISSUE THREAD

**Issue by mnsc** [MicrosoftDocs/mslearn-staticwebapp#22]
I ran `npm run serve` on my machine and the build failed with the following. 
```
 ERROR  Failed to compile with 1 errors                                                                                                                                                             9:08:38 PM

 error  in ./src/views/products/product-list.vue

Module Error (from ./node_modules/eslint-loader/index.js):

/home/mattias/labbaswa/aswa-learn/vue-app/src/views/products/product-list.vue
  34:34  error  Replace `⏎······Loading·data·...⏎····` with `Loading·data·...`  prettier/prettier

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

```

I ran `npm run lint -- --fix` and that fixed it for me. I had the same problems building with github actions and when I pushed my commits with the lint-fix the following build worked. 

My repo that I created from this template: https://github.com/mnsc/aswa-learn

**Comment by johnpapa** [comment]
Thanks for reporting this. I am not sure why I dont see this error yet you do. I wonder if its a Windows vs macOS thing. What OS do you have?

**Comment by johnpapa** [comment]
I added a pre commit hook to the vue app to have it run the lint fixer. this should "fix" it
