### ISSUE TITLE
React-app build fails for reason could not detect the language from repo

### ISSUE THREAD

**Issue by jarivainola** [MicrosoftDocs/mslearn-staticwebapp#32]
Trying to get react-app workflow to build but it fails for reason could not detect the language from repo. Please find logs below.
Found something similar here https://github.com/MicrosoftDocs/vscodespaces/issues/85

Run Azure/static-web-apps-deploy@v0.0.1-preview
...
App Directory Location: '/' was found.
[WARNING] Api Directory Location: 'api' could not be found. Azure Functions will not be created.
Starting to build app with Oryx
Azure Static Web Apps utilizes Oryx to build both static applications and Azure Functions. You can find more details on Oryx here: https://github.com/microsoft/Oryx
---Oryx build logs---

Operation performed by Microsoft Oryx, https://github.com/Microsoft/Oryx
You can report issues at https://github.com/Microsoft/Oryx/issues

Oryx Version: 0.2.20201112.1, Commit: a120bb248aa8d208ca5e02d7d9d075196e79cffd, ReleaseTagName: 20201112.1

Build Operation ID: |GAlwqTp1cA0=.298d1e3d_
Repository Commit : c8eee2b1fa80a879adb01693d6710c959ac9e49a

Detecting platforms...
Could not detect any platform in the source directory.
Error: Could not detect the language from repo.

---End of Oryx build logs---
Oryx was unable to determine the build steps. Continuing assuming the assets in this folder are already built. If this is an unexpected behavior please contact support.
Finished building app with Oryx

**Comment by gcoines-uoc** [comment]
I faced the same issue. Inspecting the code at [https://github.com/Microsoft/Oryx](https://github.com/Microsoft/Oryx) source code, I realized that Oryx tries to identify a node based app checking if there's a package.json file under the app path you've specified in your settings.

¿Could you check you've properly set the path to your app's folder within your .yml file? 

For instance, if your project folder has this structure:

- /
-   public/
-   src/
-   **package.json**

then your settings within a .yml file should be -> app_location: "/" output_location: "dist"

In case your folder structure has more levels, for instance:

- /
- /app1
- /app2
- /**app3**
-   public/
-   src/
-   **package.json**

then your settings within a .yml file should be -> app_location: "/**app3**" output_location: "/**app3**/dist"

This worked for me. If you don't get it running with my suggestion, could you please share the specifics of your project structure?

Cheers.

**Comment by t-rhex** [comment]
I was having the same issue. For me,Its mostly because I didn't select location for the application and didn't select output folder where the files will be built for production. Please follow step 6-10 and it should work without problem. After naming the app on step 5, click on custom rather than react or angular. Hope that helps.

**Comment by jarivainola** [comment]
Thanks for providing these suggestions. File package.json exists and project folder structure was like the one in first example. I think the issue might have been in the path settings. And I was using react instead of custom.
I tried again the learning module and now I was able to deploy (and redeploy) successfully webapp by following the instructions.

**Comment by nutmix** [comment]
I have had no luck trying to get a hello world html page to build or deploy.  Project structure is:

/index.html
/my.js
/my.css
/xxx.yaml <= generated by azure portal.

the yaml build file is in the root, with the following content:

`
  - task: AzureStaticWebApp@0
    inputs:
      azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_xxxx)
      app_location: "/" # App source code path
      api_location: "" # Api source code path - optional
      output_location: "" # Built app content directory - optional
`

The error message is:

`
Detecting platforms...
Could not detect any platform in the source directory.
Error: Could not detect the language from repo.
`

Any ideas how to fix?
