### ISSUE TITLE
Dependency missing for azure functions

### ISSUE THREAD

**Issue by Frank683** [MicrosoftDocs/mslearn-staticwebapp#4]
When following the tutorial the step where the azure functions are to be started locally with `npm start` in the ./api folder fails because the Azure Function Core Tools are missing.

They are not listed as dependency in api/package.json and the tutorial doesn't list it as a prerequisite either.

Finally I found instructions how to make it work [here](https://www.npmjs.com/package/azure-functions-core-tools)

**Comment by SteveALee** [comment]
but no clue whether to use v2 or v3 and no documented release process so we know if master is release or working branch.

**Comment by adebiyial** [comment]
You need to install the Azure Function Core Tools globally.

Yarn: `yarn global add azure-functions-core-tools` or 
npm: `npm i -g azure-functions-core-tools`

**Comment by johnpapa** [comment]
yes, as @adebiyial says the functions core tools are required. These are listed in the first page of the Learn tutorial (I know it can easily be missed). I recently also added a reminder for this on the exercise for functions.
