### ISSUE TITLE
Excessive GitHub access requested

### ISSUE THREAD

**Issue by SteveALee** [MicrosoftDocs/mslearn-staticwebapp#5]
I realise this is possibly a static apps or GitHub issue and I don't really understand the GitHub access system but when I created the Sandbox resource it requested what appears to be excessive access to GitHub. Many of my organisations have a green tick next to then with no way to disable. 

Perhaps GitHub settings or the organisations settings default to allowing access. Perhaps it is safe as I have to grant explicit access later? Whatever, i'd be much happier if it was only given access to my account where I will create the repo, not any organsiations I am a member of.

![image](https://user-images.githubusercontent.com/618922/82477874-f5ba0600-9ac7-11ea-8ba3-3abfcb4b2bc5.png)

**Comment by johnpapa** [comment]
Thanks for opening this issue. You can open this issue in https://github.com/azure/static-web-apps as it likely relates to your SWA experience.
