### ISSUE TITLE
mslearn-staticwebapp repository doesn't exist api-starter folder

### ISSUE THREAD

**Issue by displaygreat** [MicrosoftDocs/mslearn-staticwebapp#52]
In the course for building static web app has been written that cloned repository contains api-starter. But mslearn-staticwebapp repository doesn't exist api-starter folder. It's not possible to pass to the next step of the course.

**Comment by eduardogoncalves** [comment]
@displaygreat  I found the API is now in another repo: https://github.com/MicrosoftDocs/mslearn-staticwebapp-api
