### ISSUE TITLE
CosmosDb bindings

### ISSUE THREAD

**Issue by magnus-hansson** [MicrosoftDocs/mslearn-staticwebapp#7]
I wonder if it should be possible to create a function with a cosmosDBbinding with Static web apps at the moment?

I get this error message when I try add a cosmosDB binding to a function:

> Error in processing api build artifacts: the file 'products-post/function.json' does not specify a valid function with only HTTP triggers and bindings. Please ensure the JSON contains a single httpTrigger input trigger and a single http output binding.

My function.json looks like this:
`
{
  "bindings": [
    {
      "authLevel": "anonymous",
      "type": "httpTrigger",
      "direction": "in",
      "name": "req",
      "methods": ["post"],
      "route": "products"
    },
    {
      "type": "http",
      "direction": "out",
      "name": "res"
    },
    {
      "type": "cosmosDB",
      "name": "inputDocumentIn",
      "databaseName": "mydb",
      "collectionName": "mycol",
      "connectionStringSetting": "CosmosDBConnectionString",
      "direction": "in",
      "sqlQuery": "SELECT * from c"
    }
  ]
}
`

**Comment by johnpapa** [comment]
Thanks for opening this issue. You can open this issue in https://github.com/azure/static-web-apps as it likely relates to your SWA experience.
